title:              The Curiosity Journal
email:              161jchan@gmail.com
description:        >
  <p>An architect needs bricks to build a house.</p>
  <p>A mind requires knowledge to innovate.</p>
  <p>Here are my bricks—interesting things I’ve learned and read, in my own words.</p>
author:             Jenny Chan
url: "https://161jchan.github.io"
baseurl: "/jenny-chan"

# Social Profiles

github_username:    161jchan
instagram_username:  jennychan333
linkedin_username: https://www.linkedin.com/in/jc-jennychan/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
